server:
  port: 8080

spotify:
  api:
    url: 'https://api.spotify.com/v1'
    authorizationUrl: 'https://accounts.spotify.com'
    clientId: 'censored'
    clientSecret: 'censored'
    redirectUrl: 'https://spring.io/'
    defaultCountryCode: 'PL'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spotify_integration
      username: 'test'
      password: 'qwert6'