server:
  port: 8080

spotify:
  api:
    url: 'https://api.spotify.com/v1'
    authorizationUrl: 'https://accounts.spotify.com'
    clientId: 'censored'
    clientSecret: 'censored'
    redirectUrl: 'https://spring.io/'
    token: 'censored'
    refreshToken: 'censored'
    defaultCountryCode: 'PL'
